name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: '[17.0,)'

      - name: Build solution
       run: msbuild "AFO2.slnx" /p:Configuration=Release /p:PlatformToolset=v143